[[check]]
name = "cargo fmt"
command = "cargo fmt --check"

[[check]]
name = "cargo clippy"
command = "cargo clippy --workspace -- -D warnings"

[[check]]
name = "cargo test"
command = "cargo test --workspace"
